### PR TITLE
Image and workflow upgrade to blender 3.4

### PR DESCRIPTION
**Pull request by alchem0x2A**
Changes
- env and main images with blender 3.4
- version check and backward compatibility hack in `install.py`
- minor change in CD/CI

### CODE REVIEW

**Comment by alchem0x2A** [comment]
@superstar54 apart from the plugin test everything else should work.

**Comment by alchem0x2A** [comment]
I see. The newer scipy / numpy packages from conda are built against gcc-7 and requires newer glibcxx. since when blender starts the conda env activate script wasn't properly called (I think that's a historical issue). A possible solution is to force adding the LD_LIBRARY_PATH pointing to conda's lib so that blenders knows that. I'll rebuild the image to see if it works.

Could you also check if the same issue happens on your local blender after using install.py (without specifying the LD_LIBRARY_PATH)? I doubt it's only specific to the image (base image is ubuntu18.04) but better double check

**Comment by alchem0x2A** [comment]
@superstar54 ready to go now!

Feel free to tag the version ( I guess v2.3.0 or directly v3.0.0 in this case?) if we don't see other systems reporting the old libstdc++ issue then I prefer not to include the LD_LIBRARY_PATH in the install.py (but may put in the doc for precaution)

**Comment by superstar54** [comment]
> Could you also check if the same issue happens on your local blender after using install.py (without specifying the LD_LIBRARY_PATH)? I doubt it's only specific to the image (base image is ubuntu18.04) but better double check

I tested on a Ubuntu 20.04. I used the `install.py` and didn't specify the `LD_LIBRARY_PATH`. I got the same error. 
```
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found
```

**Comment by superstar54** [comment]
If I specified the `LD_LIBRARY_PATH` before installation, the error  gone and the installation completed successfully. But when I open another terminal (`LD_LIBRARY_PATH` does not validate anymore), batoms fails again. 

I remember the same error happened when I install batoms on CSCS. I need to re-install sicpy/numpy to remove the error.

**Comment by superstar54** [comment]
Yes, after merging this PR, let's go to `v2.3.0`. :smile:

**Comment by alchem0x2A** [comment]
> > Could you also check if the same issue happens on your local blender after using install.py (without specifying the LD_LIBRARY_PATH)? I doubt it's only specific to the image (base image is ubuntu18.04) but better double check
> 
> I tested on a Ubuntu 20.04. I used the `install.py` and didn't specify the `LD_LIBRARY_PATH`. I got the same error.
> 
> ```
> ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found
> ```

understand. there could be several solutions I can think of:
1) Downpin scipy to some lower version in install.py
2) Add a comment asking user to add `LD_LIBRARY_PATH` to bashrc at the end of the install.py

messing the conda environment with pip-distributed scipy is probably discouraged as user may end up in a limbo state. appreciate your feedback

**Comment by superstar54** [comment]
Better to make it automatic and not to use the old scipy version. I suggest re-installing `numpy` and `scipy` after making the symlink in the `install.py`. Line 948.

```python
    # re-install numpy and scipy
    blender_py = _get_blender_py(blender_bin)
    blender_py = str(blender_py)
    pip_prefix = [blender_py, "-m", "pip"]
    commands = pip_prefix + [
        "uninstall",
        "-y",
        "numpy",
        "scipy",
    ]
    proc = _run_process(commands)
    commands = pip_prefix + [
        "install",
        "--no-input",
        "numpy",
        "scipy",
    ]
    proc = _run_process(commands)
    # Step 4: install plugin
```

**Comment by alchem0x2A** [comment]
makes sense. as a backup let me implement both in `install.py`
1) Install first by conda, detect if there are importing issues. Then replace with pip version if needed. (this can be disabled by switch `--no-pip`
2) Provide an alias for `blender` in the `$CONDA_PREFIX/bin` using similar format as [`blender-softwaregl`](https://github.com/blender/blender/edit/main/release/bin/blender-softwaregl). This alias will set the `LD_LIBRARY_PATH` only during the runtime of blender and when the conda env is activated. This will be the default inside our image

I'll keep the alias and `--no-pip` option availble for users who do not want to mess the conda / pip hybrid installation.

**Comment by superstar54** [comment]
> messing the conda environment with pip-distributed scipy is probably discouraged as user may end up in a limbo state.

Yes, you are right. There is a risk that the dependency breaks. 

@alchem0x2A, it seems there is no perfect solution for the moment. I am OK with all the solutions. The decision is up to you.

**Pull request merged**
