### PR TITLE
Refactor install.py to be ready for v2.3.0

### PR DESCRIPTION
**Pull request by alchem0x2A**
Refactor and modularization of install.py

- [x] Wrap single steps in `install()` and `uninstall()` functions as unit functions that takes `parameters` as common argument 
- [x] Allow `--use-pip` on all platforms. No more manual `spglib` installation >= 2.0.0
- [x] Create a bash entry point `blender` to wrap `LD_LIBRARY_PATH` for original blender binary (unit-only)
- [x] Create bash alias `blender` under current conda environment (unix-only) 
- [x] Refactor message output and add `--dry-run` option
- [x] Installation by git hastag now working

Changes to doc should be minimal (use should care less about behind-the-scene things like alias)

### CODE REVIEW

**Comment by alchem0x2A** [comment]
@superstar54 could you try on your local and see if it works as usual?

**Comment by superstar54** [comment]
I got this error when run `pytest`.
```
/home/xing/bin/blender: 20: exec: /home/xing/bin/blender.origin: not found
```
The reason could be that I set my own `blender` executor in `/home/xing/bin` to execute the blender with some customized options. And the original blender is in `/home/xing/apps/blender-3.4.1-linux-x64/`. So the `blender` executor and the `blender.orgin` are not in the same folder.

After `export PATH="/home/xing/apps/blender-3.4.1-linux-x64/:$PATH"`, the `pytest` run well.

**Comment by alchem0x2A** [comment]
interesting case. what are the contents of `~/bin/blender`? I assume it will call `~/blender-3.4.1-linux-x64/blender` and the latter calls `blender.origin` at its same level of directory. For some reason the way `~/bin/blender` calls the actual binary made the search path looking for `blender.origin` at `~/bin` instead.

**Comment by alchem0x2A** [comment]
@superstar54 all tests pass now. hope that also works on your local setups

**Review by superstar54 — APPROVED** [review]
Thanks! it works.

**Pull request merged**
