### PR TITLE
change unit system to None in startup

### PR DESCRIPTION
**Pull request by alchem0x2A**
#124 The only change is to add the unit system to "NONE" in the startup file. No changes in the `preference.py` is needed

### CODE REVIEW

**Review by superstar54 — COMMENTED** [review]
Because the startup.blend is a binary file, an update will result in an overwrite, making the repository size increase a lot. We should try to avoid making changes to it.

Better to set in the `preference.py`. 
```
class BatomsDefaultPreference()
    ...
    # unit
    bpy.data.scenes["Scene"].unit_settings.system = "NONE"
    ...
```

**Comment by alchem0x2A** [comment]
seems like the settings are working when added to `BatomsDefaultStartup.execute`

**Comment by superstar54** [comment]
What is `BatomsDefaultStartup.execute`? You mean `BatomsDefaultPreference`?

Better not merge this PR, because the big `startup.blend` file is overwritten in the commits. I suggest making another PR, which only changes the `preference.py` file.

**Comment by alchem0x2A** [comment]
Per my test this line should be added to BatomsDefaultStartup  rather than BatomsDefaultPreference, otherwise the setting in scene is not saved. Better add a unit test to check the default preference / startup actually works.

I've reverted the startup.blend so after the PR there should be no new files added to main branch. But let's wait till tests pass

**Review by superstar54 — APPROVED** [review]
Yes, you are right. Should be added to `BatomsDefaultStartup`.

It is ok to merge.

**Pull request merged**
